#!/usr/bin/env php
<?php

use Symfony\Bridge\Twig\Command\LintCommand;
use Symfony\Component\Console\Application;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

require_once __DIR__ . '/vendor/autoload.php';

$twig = new Environment(new FilesystemLoader(__DIR__));

(new Application())
    ->add($command = new LintCommand($twig))
    ->getApplication()
    ->setDefaultCommand('lint:twig', true)
    ->run();
